package org.apache.derby.impl.jdbc;

import java.security.Permission;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Driver;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import org.apache.derby.iapi.jdbc.AuthenticationService;
import org.apache.derby.iapi.jdbc.BrokeredConnection;
import org.apache.derby.iapi.jdbc.BrokeredConnectionControl;
import org.apache.derby.iapi.services.context.ContextService;
import org.apache.derby.iapi.sql.ResultColumnDescriptor;
import org.apache.derby.iapi.sql.ResultSet;

public interface InternalDriverInterface extends Driver{

	public ContextService getContextServiceFactory();

	public boolean isActive();

	public Statement newEmbedStatement(EmbedConnection embedConnection, boolean b, int setResultSetType,
			int resultSetConcurrency, int resultSetHoldability);

	public PreparedStatement newEmbedPreparedStatement(EmbedConnection embedConnection, String sql, boolean b,
			int setResultSetType, int resultSetConcurrency, int resultSetHoldability, int autoGeneratedKeys,
			int[] columnIndexes, String[] columnNames) throws SQLException;

	public CallableStatement newEmbedCallableStatement(EmbedConnection embedConnection, String sql,
			int setResultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

	public DatabaseMetaData newEmbedDatabaseMetaData(EmbedConnection embedConnection, String url) throws SQLException;

	public void checkSystemPrivileges(String user, Permission dp);

	public AuthenticationService getAuthenticationService();

	public Connection getNewNestedConnection(EmbedConnection conn);

	public EmbedResultSet newEmbedResultSet(EmbedConnection conn, ResultSet executionResultSet, boolean b,
			EmbedStatement embedStatement, boolean c) throws SQLException;

	public EmbedResultSetMetaData newEmbedResultSetMetaData(ResultColumnDescriptor[] columnInfo);

	public BrokeredConnection newBrokeredConnection(BrokeredConnectionControl control) throws SQLException;

}
